[package]
name = "guest_code"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.3", default-features = false, features = ['std','getrandom'] }
rsa = "0.9.6"
rand = "0.8"
pem = "1.0.0"
num-bigint = "0.4.6"
num-traits = "0.2"